[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "bf9ca1821e7aebe22b8cffb7fd183b48ece0fbb5"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "3ee12558a3a30a7fc76cc6f2d58c097042d96d80286eb8dbd6fd66ba921a2725"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "61d8a153b92f3266307c53e9c38c6bf93a56f1e8"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "3dd3aa51b633820c8140d6b2ffa9312fc03b0126bebcdce069ec579cfb7705c3"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "725fe967013cbce83e09bde881fdf84a669fc0d1"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "c40c107def03f208fc3a1c8e2b888bf396b1d5fe261f54840c6e7be9e013efa2"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a9d564ad78d0d2d19c46c0df1e9a02d47cc2d6b"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "8bee21ab6de5609562fcb5218c0ec502561a86df121a4cd69c46e6193717498a"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb5959b889c6a246cba87911260ee6f397294978"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "6cf8c35cd58635b830928fb803632305857ae713b304912b9ab1ebe698794ae7"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96ed89ce88491240c6d60542e22c630e2544e8ae"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "8f91ddd52a7a529798f1d0ef3808d972259617729f4c10e4c7297629c7394938"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "55cf14d9446ac3d3830fb1989b53f43416aee62e"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "d033cc35b918bccae555538ce581e34bcb31b24c3cdc6682c6acb5347c4adeff"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "8a11b3b70e83d9b633305c5e89aa0709fe180daa"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "bd50be7d5be13066201e7335071ff9e3197599843a218cdd7de9b2bee39732df"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "7dcdda8ef19837a0ec21e788a5fd19319b644d9a"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "25acc7c6759e550e894a8af1d00df6a93be7192c662c20ecffd3f11866ea0688"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd38d76ced277fa41aaf4b52a3c80377f4d31f69"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "666835e70ff09049687fdcacdfa2973f9044e60709819ce1856fea310d3143c7"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35cdcc9a796435d6107580283e7ad6e8605a326c"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "85a03fffde7e511e74456685f83d0597da61c20eca656277dfdaee8d263e4cd1"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fafedd80bd63e96dc5eea42bbc3ba2d0315fb4e"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "922347a16113387f44efbc4c7bcd3a91cd66f0fc57aa12dcc663a55ad976cd5e"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "ccad52ddfff19ddec6636d5cc0ea1425327bb882"
julia_version = "1.10.0"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "5ceae0754e80cddc936baa9d1a664fd8b1a212a64b230e8fd592041092290d37"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "f53837629ce7f87ac2042e43293cdc3c6aed99f2"
julia_version = "1.11.1"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "0691d3318619e13653f564dbf7fda15024ce6717f832e1613a4db8962bae7291"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "3be32ef27c549e1e48a20d2b74606ab66fa96352"
julia_version = "1.12.0"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "1714c68ec7f39f5045283f0bcb818a3d7997f8ea7b94300fd200a4960d811546"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3277855b4b8ca4cd7c9d80604bad2ad517f5b9aa"
julia_version = "1.10.0"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "dc965ed0e3fd475eb8d810eb046c022ee8adbd7a229325527448c7fa95c39e9f"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06b591811703d1fea0f496c9b1aafb8de9b8e90c"
julia_version = "1.11.1"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "f7fc4eafb3be2d676c2a780898b1f31f79e517ff3330e8a80ff815ef2a816197"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cde66a6c13adbbab6187cf675bcc60381b01cc1f"
julia_version = "1.12.0"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "8c1e9628544a72cccf43ac0bafefe17daf1b369253e75df7c05549769f8a413f"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.4.0+0/openfhe_julia_int128.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
