[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "2282388dfd60e509f55bd7fde289575b6c3addf0"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "29ac6c120b271ad263054d4503a4cbce111452e44016d2d677642460180180d4"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "c147fb27ef884a5bce17291272871153fc625544"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "315315241f98ae5ef540c30ad56968440554aa57630b8215d621d59f4abd87a7"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
git-tree-sha1 = "bcb6131ec97a4e7db925deec147171c272523f25"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "25fc403ccc10d579a91ff8eb13b0db67ead2f954305bfca639cc9f348b62a243"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de35955e10101e12774bd9ab6dfd66d1451010cc"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "d7e6c98003be57ab0d0835499adc7613bcaf9cbc1859a6e88f3294d0d864cd60"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6564a5b551ee50f0afa5a4b58edcbc1b59cce9db"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "da4470b8f202df1d87209d1c27aabc28aec4d46bff99c603c84df35277282ce2"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b66f9e715009be03acc3335417bddba878c99c3"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "d8ba80eb3c8b6528ceba0304fb972bcb3996ce587cd86807cbdbd52ba23a1eba"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56a9339083ae4492a2ec6dcc51b4a74996bd992f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "4ee4589cb97bc9dd9f9eca6938473829240311d3183ec4da2b3d29bc42a719e3"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7733cc1086c61b552ac1bd9c53e478793f701dfd"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "6563d21c61e3ddd145985be0bd3338926289687448e0e6887524009e3a8f5656"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c59d91b8f6cbfdaace492ddacdcb39afb5fbf70f"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "5f27840ca831205c4232c221c9efaf633b289d4c3db278936a6bc032a5ac9d9b"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "3c24844f800137d321389bf5e966eae086748fae"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "56fa2213497f5b2b6af224eb0ca039b5cfeb8647dafaa13f764fbf0e75d7d575"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "75e90b3019862b65a76711d3319cbed4405986a9"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "aff0c81142ba0d54721a414e624551599f3f29b29a45bb74baa7ab2706ec1f80"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "a9e206c91580c08693826d37c79305dc465f8a3e"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia_int128.download]]
    sha256 = "3de8b8cbe650d35bc5925558906e79f309b556aa726ca6db6534b6cdf81ec755"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ca0bd9fc44838514be55743e4f1d23c9472c886"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "d1fc6d2b638ebf322d5576fc886c7d30b8dfa9b92ad2a04e584c53f73b21cdb0"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa1f74c89d95c2caddabfe4c5227a61c1de57ab2"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "935812154941121ef7ffaaf9fe47fdb4ab4cb7a9c84cf53e1b7be4c31f95f6ea"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97b8ea715e62080ecba23d3b7d5e562ffcab61e1"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "d5925996394d762d126fc8276f5c19b2ea86a877bca45ef57d5dea95862d5203"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c845d7804d970a0ef5d005d49eb8dad8f55495fe"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "fda88e7b46391081d0c95d98b3e51aef470122cedd2209c55bfa9ebc9c0f7b49"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e3b825c180ab6ef240c70809d76cbfb518bf8ee"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "900642eb9baa30627bbea94df4819f3c14a0227833a4b0acdd60f2639b9b606a"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "274e42e0376ec9d80c23624d046cd09b2341d292"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia_int128.download]]
    sha256 = "2ac086e9ef0319e5275a6d1bcba58d2ff098b0ae352cdc49dc9782d8b9989612"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "aa63a2317ac39c40fe009626a7a71d07b9e5d52c"
julia_version = "1.10.0"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "eb930100975a62c2e97ddfc502a829d323427a4a5000ea1a5a1bed246f565d3d"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "cbe9bd16ebf8175f42bcbc9e6fe1d43a8f68eb9d"
julia_version = "1.11.1"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "905704a7e2b08c2f7d3393416b8ab761e2cc9bc306289c0f638c4bd86b2090b3"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
git-tree-sha1 = "87e7d8930c1134c17f64a3286f52a41c11d9414f"
julia_version = "1.12.0"
os = "freebsd"

    [[openfhe_julia_int128.download]]
    sha256 = "0582be9be8687a71fb0495aad1f50ca9c894669fb312302949f17c09e2a16f4f"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfae864b5295eb0caa190ed972ac1a1ff91d1281"
julia_version = "1.10.0"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "77c7526150e869d75bcbe0f68ab5870ff20d275eac53ab8757fb8c6cd49d5e47"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2536a7f2dd369db6a2907a882fcd992add2a0f1f"
julia_version = "1.11.1"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "4701eaff27ecc363bdf05ac020833f0477cddd1850cf918105265bd6e15c9351"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-w64-mingw32-cxx03-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bc68bc473b4dbe37193e6046334bcbe827ecc99"
julia_version = "1.12.0"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "aaf597f9b90aa873fd358e84473c5466d512181ec8342e748bdb64a6976f40ab"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-w64-mingw32-cxx03-julia_version+1.12.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "350669d082b2e888376258f37796d2f769fa1f9d"
julia_version = "1.10.0"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "42f40b5876dd6f5d2daf5322541f10bb7a76eb432d80990a16ec468eb2ba2d68"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6b7605fc2eeecac3ccddb294270d45e4033b8d0"
julia_version = "1.11.1"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "911e3ec0eddda3c5ed76fdcbebe3f4024c5cd819ada8fe77d804715b98c32828"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7676e2ab942ae43eba3094236ff7b27f55c61223"
julia_version = "1.12.0"
os = "windows"

    [[openfhe_julia_int128.download]]
    sha256 = "1a2720f5d55c5c50662bcb5368584fa4c2c522ee7049aa974c6f10e4a72219cb"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_int128_jll.jl/releases/download/openfhe_julia_int128-v0.3.10+0/openfhe_julia_int128.v0.3.10.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
